
class Relacionales {
    public static void main(String[] args) {
        
        int a = 10;
        int b = 20; 
        
        System.out.println("a == b = " + (a == b ) );
        System.out.println ( "a != b = " + (a != b) ); 
        System.out.println ( "a > b = " + (a > b) );     
        System.out.println ( "a < b = " + (a < b) ); 
        System.out.println ( "a >= b = " + (a >= b) ); 
        System.out.println ( "a <= b = " + (a <= b) ); 
    }
}

// ==comprueba si dos valores son iguales 
// =! Comprueba si dos valores no son iguales 
// > Comprueba si el valor izquierdo es mayor 
// < Comprueba si el valor izquierdo es menor 
// >= Comprueba si el vaor izquierdo es mayor o igual que el derecho 
// <= Comprueba si el  vaor izquierdo es menor o igual que el derecho 

//devuelven un resultado de tipo booleano (true o false).